name: testapp
description: "A new Flutter project."
# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Application version
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  syncfusion_flutter_gauges: ^20.4.43
  fl_chart: ^0.40.0
  syncfusion_flutter_charts: ^20.4.54
  intl: ^0.18.0
  syncfusion_flutter_core: ^20.4.54
  shared_preferences: ^2.2.0
  path_provider: ^2.0.9
  flutter_secure_storage: ^5.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
